language: python
python:
  - "2.6"
  - "2.7"
  # Disable testing 3.2 since autobahn uses unicode literal syntax that wasn't
  # re-added into 3.3.  See PEP 414
#  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install .
  # Our test server uses autobahn
  - pip install autobahn
  # For 2.x, our server needs twisted
  - pip install twisted
  # For 3.x where x < 4, our server needs trollius
  - pip install trollius
script: python tests/test_pusherclient.py

